In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load The Dataset

In [16]:
dataset = pd.read_csv('used_cars.csv')
dataset

,Unnamed: 0,id,url,region,region_url,price,year,manufacturer,model,condition,...,drive,size,type,paint_color,image_url,description,county,state,lat,long
0,0,7034441763,https://saltlakecity.craigslist.org/cto/d/salt...,salt lake city,https://saltlakecity.craigslist.org,17899,2012.0,volkswagen,golf r,excellent,...,4wd,compact,hatchback,black,https://images.craigslist.org/00G0G_fTLDWM5Xyv...,PRICE REDUCED! -Garage kept -Low Miles (63K)...,NaN,ut,40.7372,-111.858
1,1,7034440610,https://saltlakecity.craigslist.org/ctd/d/sand...,salt lake city,https://saltlakecity.craigslist.org,0,2016.0,ford,f-150,excellent,...,4wd,NaN,NaN,NaN,https://images.craigslist.org/00v0v_7Cu0buIofU...,Drive it home today. Call (Or Text) us now !!C...,NaN,ut,40.5881,-111.884
2,2,7034440588,https://saltlakecity.craigslist.org/ctd/d/sand...,salt lake city,https://saltlakecity.craigslist.org,46463,2015.0,gmc,sierra 1500,excellent,...,4wd,NaN,NaN,white,https://images.craigslist.org/01515_lPvJ9bfbdY...,Drive it home today. Call (Or Text) us now !!C...,NaN,ut,40.5881,-111.884
3,3,7034440546,https://saltlakecity.craigslist.org/ctd/d/sand...,salt lake city,https://saltlakecity.craigslist.org,0,2016.0,ford,f-150,excellent,...,4wd,NaN,NaN,NaN,https://images.craigslist.org/00T0T_6Rjfp3NS4O...,Drive it home today. Call (Or Text) us now !!C...,NaN,ut,40.5881,-111.884
4,4,7034406932,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,49999,2018.0,ford,f-450,NaN,...,4wd,NaN,pickup,white,https://images.craigslist.org/00W0W_8yIUwRBXXd...,2018 Ford F-350 F350 F 350 SD Lariat Crew Cab ...,NaN,ut,40.3744,-104.694
5,5,7034406582,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,13999,2009.0,ram,NaN,NaN,...,4wd,NaN,pickup,silver,https://images.craigslist.org/00y0y_RR9x2lk7eh...,"2009 RAM 1500 4WD Quad Cab 140.5"" ST"" Offe...",NaN,ut,40.3744,-104.694
6,6,7034405619,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,34500,2017.0,ford,f-350,NaN,...,4wd,NaN,pickup,white,https://images.craigslist.org/00k0k_lIBatiU90s...,2017 Ford Super Duty F-350 F350 F 350 SRW Crew...,NaN,ut,40.3744,-104.694
7,7,7034405349,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,14500,2007.0,gmc,sierra,NaN,...,4wd,NaN,pickup,NaN,https://images.craigslist.org/00202_jTNQzQVWZs...,2007 GMC Sierra 1500 SLE Crew Cab 4WD Offe...,NaN,ut,40.3744,-104.694
8,8,7034404595,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,12500,2013.0,ford,f-250,NaN,...,4wd,NaN,pickup,white,https://images.craigslist.org/00F0F_99lwfqrZWc...,2013 Ford F-250 F250 F 250 SD XLT 4WD Offe...,NaN,ut,40.3744,-104.694
9,9,7034401857,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,34500,2012.0,ram,NaN,NaN,...,4wd,NaN,pickup,silver,https://images.craigslist.org/00a0a_1cDSDtUsLA...,"2012 RAM 2500 4WD Mega Cab 160.5"" Laramie Long...",NaN,ut,40.3744,-104.694
10,10,7034401494,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,5900,1994.0,ford,f-250,NaN,...,4wd,mid-size,pickup,white,https://images.craigslist.org/00404_hGcR2zYuCD...,1994 Ford F-250 F250 F 250 Ext. Cab Offere...,NaN,ut,40.3744,-104.694
11,11,7034400341,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,16500,2013.0,gmc,yukon,NaN,...,4wd,NaN,SUV,silver,https://images.craigslist.org/00u0u_9zDdmAS5cY...,2013 GMC Yukon XL SLT 4WD Offered by: Fres...,NaN,ut,40.3744,-104.694
12,12,7034398060,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,14500,2007.0,toyota,tundra,NaN,...,4wd,NaN,pickup,NaN,https://images.craigslist.org/00o0o_iJdqqziOHf...,2007 Toyota Tundra 4WD SR5 Offered by: Fre...,NaN,ut,40.3744,-104.694
13,13,7034396354,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,27999,2015.0,gmc,sierra,NaN,...,4wd,NaN,pickup,brown,https://images.craigslist.org/00I0I_ku9cvxJLDx...,"2015 GMC Sierra 1500 4WD Crew Cab 147"" SLE"" ...",NaN,ut,40.3744,-104.694
14,14,7034395505,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,14999,2004.0,ram,NaN,NaN,...,4wd,NaN,pickup,blue,https://images.craigslist.org/00Q0Q_2roOdQb70D...,"2004 Dodge Ram 2500 4WD Crew Cab 149"" ST"" ...",NaN,ut,40.3744,-104.694
15,15,7034395342,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,24999,2014.0,ram,2500,NaN,...,4wd,NaN,pickup,white,https://images.craigslist.org/00a0a_9CLDPrKZs2...,"2014 RAM 2500 4WD Crew Cab 149"" ST"" Offere...",NaN,ut,40.3744,-104.694
16,16,7034394805,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,35500,2015.0,gmc,sierra,NaN,...,4wd,NaN,pickup,black,https://images.craigslist.org/01717_4dAxzBQc98...,2015 GMC Sierra 3500HD Denali HD Offered b...,NaN,ut,40.3744,-104.694
17,17,7034385254,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,8999,2002.0,chevrolet,silverado,NaN,...,4wd,NaN,pickup,white,https://images.craigslist.org/00O0O_6fFXrj0UAc...,2002 Chevrolet Chevy Silverado 2500 LS Off...,NaN,ut,40.3744,-104.694
18,18,7034384679,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,5999,2003.0,mercedes-benz,s-class,NaN,...,NaN,full-size,sedan,silver,https://images.craigslist.org/00W0W_d28VnZ5Gnz...,2003 Mercedes-Benz S-Class 4dr Sdn 5.0L Of...,NaN,ut,40.3744,-104.694
19,19,7034384490,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,63500,2019.0,ford,f-350,NaN,...,4wd,NaN,pickup,black,https://images.craigslist.org/00l0l_fpXTJFYJlu...,2019 Ford Super Duty F-350 F350 F 350 SRW 4WD ...,NaN,ut,40.3744,-104.694
20,20,7034384400,https://saltlakecity.craigslist.org/ctd/d/evan...,salt lake city,https://saltlakecity.craigslist.org,13500,2010.0,gmc,sierra,NaN,...,4wd,NaN,pickup,silver,https://images.craigslist.org/00p0p_gC7fmKPz4P...,2010 GMC Sierra 2500 SLE Ext. Cab Long Bed 4WD...,NaN,ut,40.3744,-104.694
21,21,7034374035,https://saltlakecity.craigslist.org/cto/d/kail...,salt lake city,https://saltlakecity.craigslist.org,31895,2008.0,jeep,wrangler rubicon unlimited,excellent,...,4wd,NaN,NaN,NaN,https://images.craigslist.org/00x0x_k7OXwwrVH8...,Jeep Wrangler Unlimited Rubicon with Burnsvill...,NaN,ut,19.7452,-155.901
22,22,7034366554,https://saltlakecity.craigslist.org/cto/d/sant...,salt lake city,https://saltlakecity.craigslist.org,9500,2001.0,ford,excursion limited,good,...,4wd,full-size,NaN,grey,https://images.craigslist.org/01111_eLtmLmhzyW...,2001 Ford excursion 7.3 190k 20k on trany 6 li...,NaN,ut,39.9542,-111.715
23,23,7034290597,https://saltlakecity.craigslist.org/ctd/d/scot...,salt lake city,https://saltlakecity.craigslist.org,57995,NaN,NaN,olet Silverado 2500HD,NaN,...,4wd,NaN,pickup,grey,https://images.craigslist.org/00E0E_1xWz0K6GU7...,2019 *Chevrolet* *Silverado 2500HD* LIFTED 201...,NaN,ut,33.4583,-111.926
24,24,7034278551,https://saltlakecity.craigslist.org/cto/d/salt...,salt lake city,https://saltlakecity.craigslist.org,4600,2008.0,honda,civic,good,...,fwd,mid-size,sedan,grey,https://images.craigslist.org/00F0F_iyJxhCTmYP...,Selling this 2008 Honda Civic 1.8L four door L...,NaN,ut,40.7499,-111.926
25,25,7034261745,https://saltlakecity.craigslist.org/ctd/d/scot...,salt lake city,https://saltlakecity.craigslist.org,32995,2014.0,gmc,sierra 1500,NaN,...,4wd,NaN,pickup,grey,https://images.craigslist.org/00T0T_fFMpcuXBYa...,2014 *GMC* *Sierra 1500* LIFTED 2014 GMC SIERR...,NaN,ut,33.4583,-111.926
26,26,7034229439,https://saltlakecity.craigslist.org/ctd/d/scot...,salt lake city,https://saltlakecity.craigslist.org,39995,NaN,NaN,ierra 1500,NaN,...,4wd,NaN,pickup,black,https://images.craigslist.org/00m0m_g6KwfhQxp8...,2018 *GMC* *Sierra 1500* LIFTED 2018 GMC SIERR...,NaN,ut,33.4583,-111.926
27,27,7034206084,https://saltlakecity.craigslist.org/ctd/d/salt...,salt lake city,https://saltlakecity.craigslist.org,26950,2015.0,ram,3500 hd,NaN,...,4wd,NaN,truck,white,https://images.craigslist.org/00D0D_hYheBp9Ph7...,Engine: 6 Cylinders Transmission: Automatic Ti...,NaN,ut,40.7476,-111.939
28,28,7034195717,https://saltlakecity.craigslist.org/ctd/d/scot...,salt lake city,https://saltlakecity.craigslist.org,39995,2016.0,chevrolet,silverado 1500,NaN,...,4wd,NaN,pickup,black,https://images.craigslist.org/00N0N_jP1bnRfbxI...,2016 *Chevrolet* *Silverado 1500* LIFTED LTZ W...,NaN,ut,33.4583,-111.926
29,29,7033845439,https://saltlakecity.craigslist.org/ctd/d/magn...,salt lake city,https://saltlakecity.craigslist.org,8300,2016.0,chevrolet,spark ev,like new,...,NaN,NaN,NaN,NaN,https://images.craigslist.org/00A0A_lcqXSKaeN1...,Great shape ALL electric Chevy Spark with 28k ...,NaN,ut,40.7009,-112.081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19971,19971,7049104380,https://kpr.craigslist.org/ctd/d/pasco-diesels...,kennewick-pasco-richland,https://kpr.craigslist.org,54999,2018.0,gmc,sierra duramax 3500 hd slt,NaN,...,4wd,NaN,truck,white,https://images.craigslist.org/00G0G_37oqrcW1sG...,Call or Text 509-412-3404 2018 GMC Sierra 350...,NaN,wa,46.2348,-119.128
19972,19972,7049103662,https://kpr.craigslist.org/ctd/d/spokane-2010-...,kennewick-pasco-richland,https://kpr.craigslist.org,19880,2010.0,ford,f-150,NaN,...,4wd,NaN,pickup,black,https://images.craigslist.org/00a0a_41fVJMXp9w...,2010 Ford F-150 F150 F 150 Platinum 5.4L V8 1/...,NaN,wa,47.6568,-117.219
19973,19973,7049093077,https://kpr.craigslist.org/ctd/d/walla-walla-2...,kennewick-pasco-richland,https://kpr.craigslist.org,0,2006.0,ram,2500,NaN,...,4wd,NaN,truck,NaN,https://images.craigslist.org/00A0A_a275z5an51...,Chrysler Dodge Jeep Ram of Walla WallaÂ Â Â Â ...,NaN,wa,46.0783,-118.293
19974,19974,7049091728,https://kpr.craigslist.org/ctd/d/pasco-2015-ch...,kennewick-pasco-richland,https://kpr.craigslist.org,9999,2015.0,chrysler,200 limited fwd gas,NaN,...,fwd,NaN,sedan,white,https://images.craigslist.org/00Y0Y_gCMwPBEHF6...,Call or Text 509-412-3404 2015 Chrysler 200 L...,NaN,wa,46.2348,-119.128
19975,19975,7049086383,https://kpr.craigslist.org/ctd/d/hermiston-for...,kennewick-pasco-richland,https://kpr.craigslist.org,0,2008.0,ford,f350 super duty crew cab,NaN,...,4wd,NaN,pickup,custom,https://images.craigslist.org/00T0T_lSHg5KgHVg...,2008 Ford F350 Super Duty Crew Cab Lariat Pick...,NaN,wa,45.8450,-119.285
19976,19976,7049086325,https://kpr.craigslist.org/ctd/d/hermiston-che...,kennewick-pasco-richland,https://kpr.craigslist.org,0,2008.0,chevrolet,silverado 1500 regular cab,NaN,...,NaN,NaN,pickup,black,https://images.craigslist.org/00h0h_93pFlfapeZ...,2008 Chevrolet Silverado 1500 Regular Cab Work...,NaN,wa,45.8450,-119.285
19977,19977,7049086264,https://kpr.craigslist.org/ctd/d/hermiston-jee...,kennewick-pasco-richland,https://kpr.craigslist.org,13385,2010.0,jeep,wrangler,NaN,...,4wd,NaN,SUV,black,https://images.craigslist.org/00o0o_6SUTNUeopN...,2010 Jeep Wrangler Sahara Sport Utility 2D - $...,NaN,wa,45.8450,-119.285
19978,19978,7049086268,https://kpr.craigslist.org/ctd/d/portland-2018...,kennewick-pasco-richland,https://kpr.craigslist.org,29995,2018.0,ford,f-150 xlt,NaN,...,4wd,NaN,truck,NaN,https://images.craigslist.org/01212_ksq9Zu2nUN...,D&M Motors LLCÂ Â Â Â Â Â Â Â STOCK #:Â Â RF72...,NaN,wa,45.5772,-122.676
19979,19979,7049061891,https://kpr.craigslist.org/ctd/d/walla-walla-2...,kennewick-pasco-richland,https://kpr.craigslist.org,0,2015.0,jeep,wrangler unlimited sahara,NaN,...,4wd,NaN,SUV,NaN,https://images.craigslist.org/00x0x_58tpO3GEqj...,Chrysler Dodge Jeep Ram of Walla WallaÂ Â Â Â ...,NaN,wa,46.0783,-118.293
19980,19980,7049054232,https://kpr.craigslist.org/ctd/d/walla-walla-2...,kennewick-pasco-richland,https://kpr.craigslist.org,0,2011.0,jeep,wrangler unlimited sahara,NaN,...,4wd,NaN,SUV,NaN,https://images.craigslist.org/00c0c_fj9izwmbVe...,Chrysler Dodge Jeep Ram of Walla WallaÂ Â Â Â ...,NaN,wa,46.0783,-118.293
19981,19981,7049086084,https://kpr.craigslist.org/ctd/d/hermiston-toy...,kennewick-pasco-richland,https://kpr.craigslist.org,0,1999.0,toyota,tacoma xtracab,NaN,...,4wd,NaN,pickup,white,https://images.craigslist.org/00F0F_iAdGQ6vTKg...,1999 Toyota Tacoma Xtracab Pickup - $0.00Call ...,NaN,wa,45.8450,-119.285
19982,19982,7049085993,https://kpr.craigslist.org/ctd/d/hermiston-che...,kennewick-pasco-richland,https://kpr.craigslist.org,0,2013.0,chevrolet,cruze,NaN,...,fwd,NaN,sedan,blue,https://images.craigslist.org/01111_fQ5dlzFaxe...,2013 Chevrolet Cruze LT Sedan 4D - $0.00Call u...,NaN,wa,45.8450,-119.285
19983,19983,7049084626,https://kpr.craigslist.org/ctd/d/pasco-2017-bm...,kennewick-pasco-richland,https://kpr.craigslist.org,22637,2017.0,bmw,330i xdrive,NaN,...,4wd,NaN,sedan,grey,https://images.craigslist.org/00303_4TnDhBihJg...,"2017 BMW 330i xDrive Sedan 4D -- $22,637 â...",NaN,wa,46.2408,-119.125
19984,19984,7049084322,https://kpr.craigslist.org/ctd/d/pasco-2017-al...,kennewick-pasco-richland,https://kpr.craigslist.org,27563,2017.0,alfa-romeo,romeo giulia,NaN,...,4wd,NaN,sedan,blue,https://images.craigslist.org/00505_kzcdtKQQmP...,"2017 Alfa Romeo Giulia Ti Sedan 4D -- $27,563 ...",NaN,wa,46.2408,-119.125
19985,19985,7049084276,https://kpr.craigslist.org/ctd/d/yakima-2017-t...,kennewick-pasco-richland,https://kpr.craigslist.org,14614,2017.0,toyota,corolla,NaN,...,fwd,NaN,sedan,NaN,https://images.craigslist.org/01111_2zHoVY5lA3...,Bud Clary Toyota of YakimaÂ Â Â Â Â Â Â Â STOC...,NaN,wa,46.5642,-120.496
19986,19986,7049084107,https://kpr.craigslist.org/ctd/d/walla-walla-2...,kennewick-pasco-richland,https://kpr.craigslist.org,0,2015.0,jeep,grand cherokee srt,NaN,...,4wd,NaN,SUV,NaN,https://images.craigslist.org/00Z0Z_eN3bQbndKd...,Chrysler Dodge Jeep Ram of Walla WallaÂ Â Â Â ...,NaN,wa,46.0783,-118.293
19987,19987,7049079049,https://kpr.craigslist.org/ctd/d/pasco-2016-fo...,kennewick-pasco-richland,https://kpr.craigslist.org,21999,2016.0,ford,explorer xlt 4x4 gas suv,NaN,...,4wd,NaN,SUV,green,https://images.craigslist.org/00000_aTydbrHtNH...,Call or Text 509-412-3404 2016 Ford Explorer ...,NaN,wa,46.2348,-119.128
19988,19988,7049078627,https://kpr.craigslist.org/ctd/d/pasco-diesels...,kennewick-pasco-richland,https://kpr.craigslist.org,47999,2015.0,chevrolet,silverado deisel 3500,NaN,...,4wd,NaN,truck,brown,https://images.craigslist.org/00u0u_2tnzMXGYBv...,Call or Text 509-412-3404 2015 Chevrolet Silv...,NaN,wa,46.2348,-119.128
19989,19989,7049073161,https://kpr.craigslist.org/ctd/d/walla-walla-2...,kennewick-pasco-richland,https://kpr.craigslist.org,0,2017.0,jeep,wrangler sahara,NaN,...,4wd,NaN,SUV,NaN,https://images.craigslist.org/00000_8Mgbkjfj5l...,Chrysler Dodge Jeep Ram of Walla WallaÂ Â Â Â ...,NaN,wa,46.0783,-118.293
19990,19990,7049068051,https://kpr.craigslist.org/ctd/d/spokane-2015-...,kennewick-pasco-richland,https://kpr.craigslist.org,12999,2015.0,mini,cooper hardtop 4 door,NaN,...,fwd,NaN,sedan,NaN,https://images.craigslist.org/00U0U_3g2kdhr0mq...,2015Â MINIÂ Cooper Hardtop 4 DoorÂ 4dr HB BMW ...,NaN,wa,47.6788,-117.407
19991,19991,7049067148,https://kpr.craigslist.org/ctd/d/coeur-alene-2...,kennewick-pasco-richland,https://kpr.craigslist.org,19498,2011.0,gmc,yukon xl denali,NaN,...,4wd,NaN,SUV,NaN,https://images.craigslist.org/00A0A_4DL2wh32xv...,Dave Smith Coeur D'AleneÂ Â Â Â Â Â Â Â STOCK ...,NaN,wa,47.6961,-116.781
19992,19992,7049065979,https://kpr.craigslist.org/ctd/d/yakima-2018-c...,kennewick-pasco-richland,https://kpr.craigslist.org,19000,2018.0,chevrolet,equinox,NaN,...,4wd,NaN,SUV,NaN,https://images.craigslist.org/00B0B_bzRZNNIfwJ...,Bud Clary Toyota of YakimaÂ Â Â Â Â Â Â Â STOC...,NaN,wa,46.5642,-120.496
19993,19993,7049065706,https://kpr.craigslist.org/ctd/d/pasco-2016-fo...,kennewick-pasco-richland,https://kpr.craigslist.org,35999,2016.0,ford,f150 lariat 4x4 half ton,NaN,...,4wd,NaN,truck,blue,https://images.craigslist.org/00D0D_5h5EbrsjAl...,Call or Text 509-412-3404 2016 Ford F150 Lari...,NaN,wa,46.2348,-119.128
19994,19994,7049053720,https://kpr.craigslist.org/cto/d/west-richland...,kennewick-pasco-richland,https://kpr.craigslist.org,2200,2005.0,nissan,murano,good,...,4wd,NaN,SUV,brown,https://images.craigslist.org/01616_iItegt4Ly3...,Great fixer upper... Starter has been giving ...,NaN,wa,46.3153,-119.371
19995,19995,7049052983,https://kpr.craigslist.org/ctd/d/pasco-2017-su...,kennewick-pasco-richland,https://kpr.craigslist.org,24999,2017.0,subaru,wrx premium awd gas sedan,NaN,...,4wd,NaN,sedan,silver,https://images.craigslist.org/00x0x_4aLQ4jnyeg...,Call or Text 509-412-3404 2017 Subaru WRX Pre...,NaN,wa,46.2348,-119.128
19996,19996,7049052853,https://kpr.craigslist.org/ctd/d/pasco-diesels...,kennewick-pasco-richland,https://kpr.craigslist.org,49999,2016.0,ram,cummin 2500 laramie,NaN,...,4wd,NaN,truck,grey,https://images.craigslist.org/00h0h_d5xQ6Q7Ygd...,Call or Text 509-412-3404 2016 Dodge Ram 2500...,NaN,wa,46.2348,-119.128
19997,19997,7049052797,https://kpr.craigslist.org/ctd/d/yakima-2018-n...,kennewick-pasco-richland,https://kpr.craigslist.org,12127,2018.0,nissan,sentra,NaN,...,fwd,NaN,sedan,NaN,https://images.craigslist.org/00Y0Y_cuQ8XIP5R4...,Bud Clary Toyota of YakimaÂ Â Â Â Â Â Â Â STOC...,NaN,wa,46.5642,-120.496
19998,19998,7049049369,https://kpr.craigslist.org/ctd/d/walla-walla-2...,kennewick-pasco-richland,https://kpr.craigslist.org,0,2019.0,jeep,grand cherokee limited,NaN,...,4wd,NaN,SUV,NaN,https://images.craigslist.org/00h0h_gvXVsydGQd...,Chrysler Dodge Jeep Ram of Walla WallaÂ Â Â Â ...,NaN,wa,46.0783,-118.293
19999,19999,7049042761,https://kpr.craigslist.org/ctd/d/yakima-2017-t...,kennewick-pasco-richland,https://kpr.craigslist.org,14661,2017.0,toyota,corolla,NaN,...,fwd,NaN,sedan,NaN,https://images.craigslist.org/00P0P_94PZlFJECu...,Bud Clary Toyota of YakimaÂ Â Â Â Â Â Â Â STOC...,NaN,wa,46.5642,-120.496
20000,20000,7049039610,https://kpr.craigslist.org/ctd/d/pasco-2019-to...,kennewick-pasco-richland,https://kpr.craigslist.org,35999,2019.0,toyota,4runner sr5 4x4 gas suv,NaN,...,4wd,NaN,SUV,black,https://images.craigslist.org/00T0T_eOxdWaPYL3...,Call or Text 509-412-3404 2019 Toyota 4Runner...,NaN,wa,46.2348,-119.128

# Data Preprocessing

### Mengambil Atribut untuk Dijadikan Dependent Variable dan Independent Variable

In [17]:
data = dataset.iloc[:,lambda dataset: [8,10,11,14,18,7]]
data #3,4,5,6,8,10,12

,model,cylinders,fuel,transmission,type,manufacturer
0,golf r,4 cylinders,gas,manual,hatchback,volkswagen
1,f-150,NaN,gas,automatic,NaN,ford
2,sierra 1500,NaN,gas,automatic,NaN,gmc
3,f-150,NaN,gas,automatic,NaN,ford
4,f-450,NaN,diesel,automatic,pickup,ford
5,NaN,NaN,gas,automatic,pickup,ram
6,f-350,NaN,diesel,automatic,pickup,ford
7,sierra,NaN,gas,automatic,pickup,gmc
8,f-250,NaN,gas,automatic,pickup,ford
9,NaN,NaN,diesel,automatic,pickup,ram
10,f-250,NaN,gas,manual,pickup,ford
11,yukon,NaN,other,automatic,SUV,gmc
12,tundra,NaN,gas,automatic,pickup,toyota
13,sierra,NaN,gas,automatic,pickup,gmc
14,NaN,NaN,diesel,automatic,pickup,ram
15,2500,NaN,diesel,automatic,pickup,ram
16,sierra,NaN,diesel,automatic,pickup,gmc
17,silverado,NaN,gas,automatic,pickup,chevrolet
18,s-class,NaN,gas,automatic,sedan,mercedes-benz
19,f-350,NaN,diesel,automatic,pickup,ford
20,sierra,NaN,gas,automatic,pickup,gmc
21,wrangler rubicon unlimited,8 cylinders,gas,automatic,NaN,jeep
22,excursion limited,8 cylinders,diesel,automatic,NaN,ford
23,olet Silverado 2500HD,8 cylinders,NaN,automatic,pickup,NaN
24,civic,4 cylinders,gas,automatic,sedan,honda
25,sierra 1500,8 cylinders,NaN,automatic,pickup,gmc
26,ierra 1500,8 cylinders,NaN,automatic,pickup,NaN
27,3500 hd,6 cylinders,diesel,automatic,truck,ram
28,silverado 1500,8 cylinders,gas,automatic,pickup,chevrolet
29,spark ev,NaN,electric,automatic,NaN,chevrolet
...,...,...,...,...,...,...
19971,sierra duramax 3500 hd slt,NaN,diesel,automatic,truck,gmc
19972,f-150,NaN,other,automatic,pickup,ford
19973,2500,6 cylinders,diesel,automatic,truck,ram
19974,200 limited fwd gas,NaN,gas,automatic,sedan,chrysler
19975,f350 super duty crew cab,8 cylinders,diesel,automatic,pickup,ford
19976,silverado 1500 regular cab,8 cylinders,gas,automatic,pickup,chevrolet
19977,wrangler,6 cylinders,gas,automatic,SUV,jeep
19978,f-150 xlt,6 cylinders,gas,automatic,truck,ford
19979,wrangler unlimited sahara,6 cylinders,gas,automatic,SUV,jeep
19980,wrangler unlimited sahara,6 cylinders,gas,automatic,SUV,jeep
19981,tacoma xtracab,4 cylinders,gas,manual,pickup,toyota
19982,cruze,4 cylinders,gas,automatic,sedan,chevrolet
19983,330i xdrive,4 cylinders,gas,automatic,sedan,bmw
19984,romeo giulia,4 cylinders,gas,automatic,sedan,alfa-romeo
19985,corolla,4 cylinders,gas,automatic,sedan,toyota
19986,grand cherokee srt,8 cylinders,gas,automatic,SUV,jeep
19987,explorer xlt 4x4 gas suv,NaN,gas,automatic,SUV,ford
19988,silverado deisel 3500,NaN,diesel,automatic,truck,chevrolet
19989,wrangler sahara,6 cylinders,gas,manual,SUV,jeep
19990,cooper hardtop 4 door,3 cylinders,gas,automatic,sedan,mini
19991,yukon xl denali,8 cylinders,gas,automatic,SUV,gmc
19992,equinox,4 cylinders,gas,automatic,SUV,chevrolet
19993,f150 lariat 4x4 half ton,NaN,gas,automatic,truck,ford
19994,murano,6 cylinders,gas,automatic,SUV,nissan
19995,wrx premium awd gas sedan,NaN,gas,manual,sedan,subaru
19996,cummin 2500 laramie,NaN,diesel,automatic,truck,ram
19997,sentra,4 cylinders,gas,automatic,sedan,nissan
19998,grand cherokee limited,6 cylinders,gas,automatic,SUV,jeep
19999,corolla,4 cylinders,gas,automatic,sedan,toyota
20000,4runner sr5 4x4 gas suv,NaN,gas,automatic,SUV,toyota

In [18]:
data.isnull().sum(axis = 0)

model            265
cylinders       7085
fuel              73
transmission     190
type            3659
manufacturer     705
dtype: int64

### Melakukan Drop NaN kepada beberapa variabel

In [19]:
data = data[pd.notnull(data['manufacturer'])]
data = data[pd.notnull(data['model'])]
data = data[pd.notnull(data['fuel'])]

In [20]:
data = data.replace(np.nan, 'NaN', regex=True)

### Memisahkan Independent variable dan Dependent variable

In [21]:
X_Independent = data.iloc[:,lambda dataset: [0,1,2,3,4]].values
Y_Dependent = data.iloc[:,5].values

### Binning Manufacturer Variable Agar Persebaran Data Merata (Menjadi Amerika & non-Amerika)

In [22]:
df = data.manufacturer.value_counts()
df

ford               3416
chevrolet          2132
toyota             1704
nissan             1302
honda              1263
jeep               1040
ram                 909
gmc                 768
subaru              718
bmw                 627
dodge               618
hyundai             531
volkswagen          503
mercedes-benz       456
kia                 392
mazda               287
chrysler            267
audi                260
lexus               248
cadillac            235
acura               196
infiniti            155
volvo               155
buick               148
mitsubishi          134
lincoln              96
pontiac              72
mini                 58
saturn               52
fiat                 50
mercury              48
rover                46
jaguar               40
harley-davidson      29
tesla                15
alfa-romeo            5
porche                1
aston-martin          1
ferrari               1
land rover            1
Name: manufacturer, dtype: int64

In [23]:
for i in range(len(Y_Dependent)):
    if Y_Dependent[i] == 'ford':
        Y_Dependent[i] = 'amerika'
    elif Y_Dependent[i] == 'chevrolet':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'toyota':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent [i] == 'nissan':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent [i] == 'honda':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'jeep':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'ram':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'gmc':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'subaru':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'bmw':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'dodge':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'hyundai':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'volkswagen':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'mercedes-benz':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'kia':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'mazda':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'chrysler':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'audi':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'lexus':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'cadillac':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'acura':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'volvo':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'infiniti':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'buick':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'mitsubishi':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'lincoln':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'pontiac':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'mini':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'rover':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'saturn':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'fiat':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'mercury':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'jaguar':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'harley-davidson':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'tesla':
        Y_Dependent[i]='amerika'
    elif Y_Dependent[i] == 'alfa-romeo':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'ferrari':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'land rover':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'porche':
        Y_Dependent[i]='non-amerika'
    elif Y_Dependent[i] == 'aston-martin':
        Y_Dependent[i]='non-amerika'

In [24]:
df = data.manufacturer.value_counts()
df

amerika        9845
non-amerika    9134
Name: manufacturer, dtype: int64

In [25]:
data

,model,cylinders,fuel,transmission,type,manufacturer
0,golf r,4 cylinders,gas,manual,hatchback,non-amerika
1,f-150,NaN,gas,automatic,NaN,amerika
2,sierra 1500,NaN,gas,automatic,NaN,amerika
3,f-150,NaN,gas,automatic,NaN,amerika
4,f-450,NaN,diesel,automatic,pickup,amerika
6,f-350,NaN,diesel,automatic,pickup,amerika
7,sierra,NaN,gas,automatic,pickup,amerika
8,f-250,NaN,gas,automatic,pickup,amerika
10,f-250,NaN,gas,manual,pickup,amerika
11,yukon,NaN,other,automatic,SUV,amerika
12,tundra,NaN,gas,automatic,pickup,non-amerika
13,sierra,NaN,gas,automatic,pickup,amerika
15,2500,NaN,diesel,automatic,pickup,amerika
16,sierra,NaN,diesel,automatic,pickup,amerika
17,silverado,NaN,gas,automatic,pickup,amerika
18,s-class,NaN,gas,automatic,sedan,non-amerika
19,f-350,NaN,diesel,automatic,pickup,amerika
20,sierra,NaN,gas,automatic,pickup,amerika
21,wrangler rubicon unlimited,8 cylinders,gas,automatic,NaN,amerika
22,excursion limited,8 cylinders,diesel,automatic,NaN,amerika
24,civic,4 cylinders,gas,automatic,sedan,non-amerika
27,3500 hd,6 cylinders,diesel,automatic,truck,amerika
28,silverado 1500,8 cylinders,gas,automatic,pickup,amerika
29,spark ev,NaN,electric,automatic,NaN,amerika
32,1500,8 cylinders,gas,automatic,pickup,amerika
35,rx,6 cylinders,gas,automatic,SUV,non-amerika
36,escalade esv,8 cylinders,gas,automatic,SUV,amerika
37,grand caravan,6 cylinders,gas,automatic,NaN,amerika
38,elantra,4 cylinders,gas,automatic,sedan,non-amerika
39,outback,4 cylinders,gas,automatic,wagon,non-amerika
...,...,...,...,...,...,...
19971,sierra duramax 3500 hd slt,NaN,diesel,automatic,truck,amerika
19972,f-150,NaN,other,automatic,pickup,amerika
19973,2500,6 cylinders,diesel,automatic,truck,amerika
19974,200 limited fwd gas,NaN,gas,automatic,sedan,amerika
19975,f350 super duty crew cab,8 cylinders,diesel,automatic,pickup,amerika
19976,silverado 1500 regular cab,8 cylinders,gas,automatic,pickup,amerika
19977,wrangler,6 cylinders,gas,automatic,SUV,amerika
19978,f-150 xlt,6 cylinders,gas,automatic,truck,amerika
19979,wrangler unlimited sahara,6 cylinders,gas,automatic,SUV,amerika
19980,wrangler unlimited sahara,6 cylinders,gas,automatic,SUV,amerika
19981,tacoma xtracab,4 cylinders,gas,manual,pickup,non-amerika
19982,cruze,4 cylinders,gas,automatic,sedan,amerika
19983,330i xdrive,4 cylinders,gas,automatic,sedan,non-amerika
19984,romeo giulia,4 cylinders,gas,automatic,sedan,non-amerika
19985,corolla,4 cylinders,gas,automatic,sedan,non-amerika
19986,grand cherokee srt,8 cylinders,gas,automatic,SUV,amerika
19987,explorer xlt 4x4 gas suv,NaN,gas,automatic,SUV,amerika
19988,silverado deisel 3500,NaN,diesel,automatic,truck,amerika
19989,wrangler sahara,6 cylinders,gas,manual,SUV,amerika
19990,cooper hardtop 4 door,3 cylinders,gas,automatic,sedan,non-amerika
19991,yukon xl denali,8 cylinders,gas,automatic,SUV,amerika
19992,equinox,4 cylinders,gas,automatic,SUV,amerika
19993,f150 lariat 4x4 half ton,NaN,gas,automatic,truck,amerika
19994,murano,6 cylinders,gas,automatic,SUV,non-amerika
19995,wrx premium awd gas sedan,NaN,gas,manual,sedan,non-amerika
19996,cummin 2500 laramie,NaN,diesel,automatic,truck,amerika
19997,sentra,4 cylinders,gas,automatic,sedan,non-amerika
19998,grand cherokee limited,6 cylinders,gas,automatic,SUV,amerika
19999,corolla,4 cylinders,gas,automatic,sedan,non-amerika
20000,4runner sr5 4x4 gas suv,NaN,gas,automatic,SUV,non-amerika

### Encode Data

In [26]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X_Independent[:, 0] = labelencoder_X.fit_transform(X_Independent[:, 0])
X_Independent[:, 1] = labelencoder_X.fit_transform(X_Independent[:, 1])
X_Independent[:, 2] = labelencoder_X.fit_transform(X_Independent[:, 2])
X_Independent[:, 3] = labelencoder_X.fit_transform(X_Independent[:, 3])
X_Independent[:, 4] = labelencoder_X.fit_transform(X_Independent[:, 4])


labelencoder_Y = LabelEncoder()
Y_Dependent = labelencoder_Y.fit_transform(Y_Dependent)

In [27]:
for i in range(len(X_Independent)):
    if X_Independent[i][1] == 7:
        X_Independent[i][1] = np.nan
    if X_Independent[i][3] == 1:
        X_Independent[i][3]= np.nan
    if X_Independent[i][4] == 0:
        X_Independent[i][4]= np.nan

### Mengisi Missing Value dengan KNN

In [28]:
from fancyimpute import KNN

Using TensorFlow backend.

In [29]:
X_filled_knn = KNN(k=3).fit_transform(X_Independent)

Imputing row 1/18979 with 0 missing, elapsed time: 48.062
Imputing row 101/18979 with 1 missing, elapsed time: 48.089
Imputing row 201/18979 with 1 missing, elapsed time: 48.108
Imputing row 301/18979 with 1 missing, elapsed time: 48.130
Imputing row 401/18979 with 1 missing, elapsed time: 48.159
Imputing row 501/18979 with 1 missing, elapsed time: 48.177
Imputing row 601/18979 with 1 missing, elapsed time: 48.200
Imputing row 701/18979 with 2 missing, elapsed time: 48.223
Imputing row 801/18979 with 1 missing, elapsed time: 48.245
Imputing row 901/18979 with 1 missing, elapsed time: 48.294
Imputing row 1001/18979 with 1 missing, elapsed time: 48.325
Imputing row 1101/18979 with 3 missing, elapsed time: 48.377
Imputing row 1201/18979 with 3 missing, elapsed time: 48.407
Imputing row 1301/18979 with 1 missing, elapsed time: 48.426
Imputing row 1401/18979 with 1 missing, elapsed time: 48.461
Imputing row 1501/18979 with 1 missing, elapsed time: 48.531
Imputing row 1601/18979 with 1 missing, elapsed time: 48.554
Imputing row 1701/18979 with 2 missing, elapsed time: 48.571
Imputing row 1801/18979 with 3 missing, elapsed time: 48.593
Imputing row 1901/18979 with 1 missing, elapsed time: 48.620
Imputing row 2001/18979 with 1 missing, elapsed time: 48.640
Imputing row 2101/18979 with 1 missing, elapsed time: 48.657
Imputing row 2201/18979 with 2 missing, elapsed time: 48.674
Imputing row 2301/18979 with 3 missing, elapsed time: 48.694
Imputing row 2401/18979 with 1 missing, elapsed time: 48.715
Imputing row 2501/18979 with 1 missing, elapsed time: 48.738
Imputing row 2601/18979 with 0 missing, elapsed time: 48.759
Imputing row 2701/18979 with 2 missing, elapsed time: 48.790
Imputing row 2801/18979 with 1 missing, elapsed time: 48.815
Imputing row 2901/18979 with 3 missing, elapsed time: 48.842
Imputing row 3001/18979 with 3 missing, elapsed time: 48.869
Imputing row 3101/18979 with 1 missing, elapsed time: 48.892
Imputing row 3201/18979 with 1 missing, elapsed time: 48.914
Imputing row 3301/18979 with 2 missing, elapsed time: 48.940
Imputing row 3401/18979 with 3 missing, elapsed time: 48.979
Imputing row 3501/18979 with 1 missing, elapsed time: 49.008
Imputing row 3601/18979 with 1 missing, elapsed time: 49.034
Imputing row 3701/18979 with 3 missing, elapsed time: 49.060
Imputing row 3801/18979 with 1 missing, elapsed time: 49.087
Imputing row 3901/18979 with 1 missing, elapsed time: 49.112
Imputing row 4001/18979 with 3 missing, elapsed time: 49.131
Imputing row 4101/18979 with 2 missing, elapsed time: 49.148
Imputing row 4201/18979 with 1 missing, elapsed time: 49.164
Imputing row 4301/18979 with 1 missing, elapsed time: 49.177
Imputing row 4401/18979 with 1 missing, elapsed time: 49.190
Imputing row 4501/18979 with 1 missing, elapsed time: 49.210
Imputing row 4601/18979 with 2 missing, elapsed time: 49.224
Imputing row 4701/18979 with 3 missing, elapsed time: 49.240
Imputing row 4801/18979 with 1 missing, elapsed time: 49.255
Imputing row 4901/18979 with 1 missing, elapsed time: 49.273
Imputing row 5001/18979 with 2 missing, elapsed time: 49.293
Imputing row 5101/18979 with 3 missing, elapsed time: 49.316
Imputing row 5201/18979 with 2 missing, elapsed time: 49.341
Imputing row 5301/18979 with 2 missing, elapsed time: 49.365
Imputing row 5401/18979 with 1 missing, elapsed time: 49.389
Imputing row 5501/18979 with 2 missing, elapsed time: 49.414
Imputing row 5601/18979 with 3 missing, elapsed time: 49.436
Imputing row 5701/18979 with 2 missing, elapsed time: 49.457
Imputing row 5801/18979 with 2 missing, elapsed time: 49.477
Imputing row 5901/18979 with 2 missing, elapsed time: 49.506
Imputing row 6001/18979 with 2 missing, elapsed time: 49.531
Imputing row 6101/18979 with 2 missing, elapsed time: 49.554
Imputing row 6201/18979 with 1 missing, elapsed time: 49.573
Imputing row 6301/18979 with 1 missing, elapsed time: 49.592
Imputing row 6401/18979 with 2 missing, elapsed time: 49.608
Imputing row 6501/18979 with 0 missing, elapsed time: 49.629
Imputing row 6601/18979 with 1 missing, elapsed time: 49.657
Imputing row 6701/18979 with 1 missing, elapsed time: 49.681
Imputing row 6801/18979 with 1 missing, elapsed time: 49.725
Imputing row 6901/18979 with 1 missing, elapsed time: 49.871
Imputing row 7001/18979 with 1 missing, elapsed time: 49.898
Imputing row 7101/18979 with 1 missing, elapsed time: 49.919
Imputing row 7201/18979 with 1 missing, elapsed time: 49.946
Imputing row 7301/18979 with 1 missing, elapsed time: 49.968
Imputing row 7401/18979 with 1 missing, elapsed time: 49.995
Imputing row 7501/18979 with 1 missing, elapsed time: 50.101
Imputing row 7601/18979 with 2 missing, elapsed time: 50.167
Imputing row 7701/18979 with 1 missing, elapsed time: 50.195
Imputing row 7801/18979 with 1 missing, elapsed time: 50.218
Imputing row 7901/18979 with 1 missing, elapsed time: 50.246
Imputing row 8001/18979 with 2 missing, elapsed time: 50.285
Imputing row 8101/18979 with 0 missing, elapsed time: 50.333
Imputing row 8201/18979 with 0 missing, elapsed time: 50.373
Imputing row 8301/18979 with 1 missing, elapsed time: 50.412
Imputing row 8401/18979 with 3 missing, elapsed time: 50.449
Imputing row 8501/18979 with 2 missing, elapsed time: 50.473
Imputing row 8601/18979 with 2 missing, elapsed time: 50.496
Imputing row 8701/18979 with 1 missing, elapsed time: 50.524
Imputing row 8801/18979 with 1 missing, elapsed time: 50.552
Imputing row 8901/18979 with 1 missing, elapsed time: 50.581
Imputing row 9001/18979 with 1 missing, elapsed time: 50.608
Imputing row 9101/18979 with 1 missing, elapsed time: 50.642
Imputing row 9201/18979 with 3 missing, elapsed time: 50.667
Imputing row 9301/18979 with 1 missing, elapsed time: 50.686
Imputing row 9401/18979 with 2 missing, elapsed time: 50.723
Imputing row 9501/18979 with 3 missing, elapsed time: 50.765
Imputing row 9601/18979 with 1 missing, elapsed time: 50.790
Imputing row 9701/18979 with 1 missing, elapsed time: 50.821
Imputing row 9801/18979 with 2 missing, elapsed time: 50.859
Imputing row 9901/18979 with 3 missing, elapsed time: 50.898
Imputing row 10001/18979 with 2 missing, elapsed time: 50.929
Imputing row 10101/18979 with 1 missing, elapsed time: 50.959
Imputing row 10201/18979 with 1 missing, elapsed time: 51.009
Imputing row 10301/18979 with 2 missing, elapsed time: 51.044
Imputing row 10401/18979 with 2 missing, elapsed time: 51.076
Imputing row 10501/18979 with 1 missing, elapsed time: 51.111
Imputing row 10601/18979 with 0 missing, elapsed time: 51.141
Imputing row 10701/18979 with 1 missing, elapsed time: 51.174
Imputing row 10801/18979 with 3 missing, elapsed time: 51.211
Imputing row 10901/18979 with 1 missing, elapsed time: 51.239
Imputing row 11001/18979 with 1 missing, elapsed time: 51.280
Imputing row 11101/18979 with 1 missing, elapsed time: 51.316
Imputing row 11201/18979 with 2 missing, elapsed time: 51.365
Imputing row 11301/18979 with 1 missing, elapsed time: 51.414
Imputing row 11401/18979 with 1 missing, elapsed time: 51.457
Imputing row 11501/18979 with 1 missing, elapsed time: 51.507
Imputing row 11601/18979 with 1 missing, elapsed time: 51.548
Imputing row 11701/18979 with 1 missing, elapsed time: 51.599
Imputing row 11801/18979 with 1 missing, elapsed time: 51.649
Imputing row 11901/18979 with 1 missing, elapsed time: 51.696
Imputing row 12001/18979 with 1 missing, elapsed time: 51.734
Imputing row 12101/18979 with 3 missing, elapsed time: 51.771
Imputing row 12201/18979 with 0 missing, elapsed time: 51.808
Imputing row 12301/18979 with 1 missing, elapsed time: 51.853
Imputing row 12401/18979 with 2 missing, elapsed time: 51.907
Imputing row 12501/18979 with 1 missing, elapsed time: 51.954
Imputing row 12601/18979 with 2 missing, elapsed time: 52.010
Imputing row 12701/18979 with 1 missing, elapsed time: 52.062
Imputing row 12801/18979 with 1 missing, elapsed time: 52.109
Imputing row 12901/18979 with 1 missing, elapsed time: 52.286
Imputing row 13001/18979 with 2 missing, elapsed time: 52.344
Imputing row 13101/18979 with 1 missing, elapsed time: 52.379
Imputing row 13201/18979 with 1 missing, elapsed time: 52.412
Imputing row 13301/18979 with 3 missing, elapsed time: 52.443
Imputing row 13401/18979 with 2 missing, elapsed time: 52.482
Imputing row 13501/18979 with 1 missing, elapsed time: 52.518
Imputing row 13601/18979 with 1 missing, elapsed time: 52.572
Imputing row 13701/18979 with 2 missing, elapsed time: 52.627

Imputing row 13801/18979 with 1 missing, elapsed time: 52.673
Imputing row 13901/18979 with 3 missing, elapsed time: 52.732
Imputing row 14001/18979 with 1 missing, elapsed time: 52.791
Imputing row 14101/18979 with 2 missing, elapsed time: 52.820
Imputing row 14201/18979 with 2 missing, elapsed time: 52.851
Imputing row 14301/18979 with 2 missing, elapsed time: 52.909
Imputing row 14401/18979 with 0 missing, elapsed time: 52.950
Imputing row 14501/18979 with 1 missing, elapsed time: 52.993
Imputing row 14601/18979 with 1 missing, elapsed time: 53.045
Imputing row 14701/18979 with 0 missing, elapsed time: 53.092
Imputing row 14801/18979 with 0 missing, elapsed time: 53.136
Imputing row 14901/18979 with 2 missing, elapsed time: 53.184
Imputing row 15001/18979 with 3 missing, elapsed time: 53.232
Imputing row 15101/18979 with 1 missing, elapsed time: 53.290
Imputing row 15201/18979 with 2 missing, elapsed time: 53.347
Imputing row 15301/18979 with 2 missing, elapsed time: 53.395
Imputing row 15401/18979 with 1 missing, elapsed time: 53.437
Imputing row 15501/18979 with 1 missing, elapsed time: 53.480
Imputing row 15601/18979 with 1 missing, elapsed time: 53.535
Imputing row 15701/18979 with 0 missing, elapsed time: 53.580
Imputing row 15801/18979 with 1 missing, elapsed time: 53.619
Imputing row 15901/18979 with 2 missing, elapsed time: 53.684
Imputing row 16001/18979 with 1 missing, elapsed time: 53.746
Imputing row 16101/18979 with 2 missing, elapsed time: 53.783
Imputing row 16201/18979 with 1 missing, elapsed time: 53.830
Imputing row 16301/18979 with 1 missing, elapsed time: 53.881
Imputing row 16401/18979 with 1 missing, elapsed time: 53.931
Imputing row 16501/18979 with 2 missing, elapsed time: 53.981
Imputing row 16601/18979 with 2 missing, elapsed time: 54.060
Imputing row 16701/18979 with 2 missing, elapsed time: 54.140
Imputing row 16801/18979 with 1 missing, elapsed time: 54.214
Imputing row 16901/18979 with 1 missing, elapsed time: 54.273
Imputing row 17001/18979 with 1 missing, elapsed time: 54.329
Imputing row 17101/18979 with 2 missing, elapsed time: 54.390
Imputing row 17201/18979 with 2 missing, elapsed time: 54.430
Imputing row 17301/18979 with 1 missing, elapsed time: 54.487
Imputing row 17401/18979 with 2 missing, elapsed time: 54.549
Imputing row 17501/18979 with 1 missing, elapsed time: 54.592
Imputing row 17601/18979 with 2 missing, elapsed time: 54.651
Imputing row 17701/18979 with 1 missing, elapsed time: 54.701
Imputing row 17801/18979 with 1 missing, elapsed time: 54.760
Imputing row 17901/18979 with 1 missing, elapsed time: 54.812
Imputing row 18001/18979 with 2 missing, elapsed time: 54.888
Imputing row 18101/18979 with 1 missing, elapsed time: 54.933
Imputing row 18201/18979 with 3 missing, elapsed time: 55.061
Imputing row 18301/18979 with 1 missing, elapsed time: 55.138
Imputing row 18401/18979 with 0 missing, elapsed time: 55.184
Imputing row 18501/18979 with 1 missing, elapsed time: 55.223
Imputing row 18601/18979 with 1 missing, elapsed time: 55.267
Imputing row 18701/18979 with 2 missing, elapsed time: 55.317
Imputing row 18801/18979 with 2 missing, elapsed time: 55.366
Imputing row 18901/18979 with 1 missing, elapsed time: 55.428

### Split Dataset Menjadi Train dan Test

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_filled_knn,Y_Dependent, test_size = 0.2, random_state = 200)

### Scalling Menggunakan Standar Scalar

In [31]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

# Klasifikasi (Random Forest)

In [32]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=5, criterion= 'entropy')
rfc.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=5,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [33]:
y_pred = rfc.predict(X_test)

# Evaluation

In [34]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.97      0.97      1971
           1       0.97      0.97      0.97      1825

    accuracy                           0.97      3796
   macro avg       0.97      0.97      0.97      3796
weighted avg       0.97      0.97      0.97      3796

In [44]:
skenario = []
for i in range(len(X_test)):
    skenario.append([X_test[i][0],X_test[i][1],X_test[i][2],X_test[i][3],X_test[i][4],Y_test[i],y_pred[i]])
np.savetxt(fname="skenarioRandomForest(Data test).csv",delimiter=',',X= skenario , header='model,cylinder,fuel,transmission,type,Y_test,Y_pred')

In [45]:
skenario = []
for i in range(len(X_test)):
    skenario.append([X_train[i][0],X_train[i][1],X_train[i][2],X_train[i][3],X_train[i][4],Y_train[i]])
np.savetxt(fname="skenarioRandomForest(Data train).csv",delimiter=',',X= skenario , header='model,cylinder,fuel,transmission,type,Y_train')